sources:
  - name: jaffle_shop
    description: This is a replica of the postgres used by our app
    database: raw
    schema: jaffle_shop
    tables:
      - name: customers
        description: One receord per customer.
      - name: orders
        description: One record per order. Includes canclled and deleted orders.

  - name: payments
    description: This is the replica of the schema used by the payment processor.
    database: raw
    schema: stripe
    tables:
      - name: payments
        description: One record per transaction
